-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 15:08:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema iv_dbtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iv_dbtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iv_dbtest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `iv_dbtest` ;

-- -----------------------------------------------------
-- Table `iv_dbtest`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`menu` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `order_index` INT(11) NULL DEFAULT '0',
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`auth` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NULL DEFAULT NULL,
  `menu_id` INT(11) NULL DEFAULT NULL,
  `permission` INT(1) NULL DEFAULT '1',
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_roleid` (`role_id` ASC) VISIBLE,
  INDEX `fk_auth_menuid` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_auth_menuid`
    FOREIGN KEY (`menu_id`)
    REFERENCES `iv_dbtest`.`menu` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auth_roleid`
    FOREIGN KEY (`role_id`)
    REFERENCES `iv_dbtest`.`role` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`product_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`product_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cate_id` INT(11) NULL DEFAULT NULL,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `img_url` VARCHAR(200) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_pinfo_cateId` (`cate_id` ASC) VISIBLE,
  CONSTRAINT `fk_pinfo_cateId`
    FOREIGN KEY (`cate_id`)
    REFERENCES `iv_dbtest`.`category` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `type` INT(1) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `qty` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(15,2) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_history_productId` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_history_productId`
    FOREIGN KEY (`product_id`)
    REFERENCES `iv_dbtest`.`product_info` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`invoice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `type` INT(1) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `qty` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(15,2) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_productId` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_productId`
    FOREIGN KEY (`product_id`)
    REFERENCES `iv_dbtest`.`product_info` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`product_in_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`product_in_stock` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NULL DEFAULT NULL,
  `qty` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(15,2) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_pinst_productId` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_pinst_productId`
    FOREIGN KEY (`product_id`)
    REFERENCES `iv_dbtest`.`product_info` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iv_dbtest`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iv_dbtest`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `role_id` INT(11) NULL DEFAULT NULL,
  `active_flag` INT(1) NULL DEFAULT '1',
  `created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_ur_user` (`user_id` ASC) VISIBLE,
  INDEX `fk_ur_role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_ur_roleid`
    FOREIGN KEY (`role_id`)
    REFERENCES `iv_dbtest`.`role` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ur_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `iv_dbtest`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
